import {Text,View,ScrollView} from 'react-native';
import {Button,Icon} from '../components/UI';
import {Action,Choices,Hint} from '../components/Common';
import {colors,styles as s} from '../theme';
import {useApp} from '../state/Store';
import {useNav} from '../navigation';
import {mastery,stageLabel,localDay} from '../engine/learning';
export function Home(){const app=useApp();const nav=useNav();const {progress:p,pack}=app;const states=mastery(pack,p);const due=states.filter(m=>m.dueAt&&Date.parse(m.dueAt)<=Date.now());const marked=p.bookmarks.filter(b=>b.active).length;const today=p.answers.filter(a=>localDay(new Date(a.at))===localDay()).length;const days=p.settings.examDate?Math.ceil((Date.parse(p.settings.examDate+'T23:59:59')-Date.now())/86400000):null;
 const start=()=>{if(app.beginStudy('Tu sesión de hoy',{count:p.settings.minutes===5?5:p.settings.minutes===10?10:15}))nav.open({name:'study'});};
 return <ScrollView contentContainerStyle={s.content}><View style={s.between}><View style={s.row}><View style={{backgroundColor:colors.green,borderRadius:10,paddingHorizontal:10,paddingVertical:3}}><Text style={{fontSize:29,fontWeight:'800',color:'#FFF'}}>L</Text></View><Text style={{fontSize:26,fontWeight:'800',color:colors.ink}}>a punto</Text></View><Text style={s.muted}>Permiso B</Text></View><View style={{gap:8}}><Text style={s.title}>{today?'Ya has dado un paso.':'Tu próximo paso.'}</Text><Text style={[s.body,{color:colors.muted}]}>{days!==null?(days>=0?`${days} días hasta tu fecha objetivo.`:'Tu fecha objetivo ha pasado. Puedes ajustarla en Mi avance.'):'Entiende, practica y vuelve a comprobar.'}</Text></View>
 {p.activeStudy?<Hint><Text style={s.heading}>Tienes una sesión a medias</Text><Text style={s.muted}>Pregunta {p.activeStudy.index+1} de {p.activeStudy.questions.length}. Tu respuesta se conserva.</Text><Button label="Retomar sesión" onPress={()=>nav.open({name:'study'})}/></Hint>:null}
 {p.activeExam?<Hint tone="orange"><Text style={s.heading}>Simulacro pendiente</Text><Text style={s.body}>El tiempo sigue contando desde que empezaste.</Text><Button label={Date.parse(p.activeExam.deadline)<=Date.now()?'Ver resultado del simulacro':'Retomar simulacro'} onPress={()=>nav.open({name:'exam'})}/></Hint>:null}
 <View style={{gap:10}}><Text style={[s.body,{fontWeight:'700'}]}>¿Cuánto tiempo tienes?</Text><Choices label="Tiempo disponible" value={p.settings.minutes} onChange={minutes=>app.update(p=>({...p,settings:{...p.settings,minutes,updatedAt:new Date().toISOString()}}))} items={[{value:5,label:'5 minutos'},{value:10,label:'10 minutos'},{value:20,label:'20 minutos'}]}/></View>
 <View style={{backgroundColor:colors.green,borderRadius:16,padding:22,gap:16}}><Text style={[s.heading,{fontSize:24,color:'#FFF'}]}>Tu sesión de hoy</Text><Text style={[s.body,{color:'#E3F2EA'}]}>{due.length?`${due.length} conceptos necesitan un repaso. Después, una situación nueva.`:'Una mezcla de conceptos nuevos, dudas y situaciones distintas.'}</Text><Button label={p.activeStudy?'Continuar aprendiendo':'Empezar sesión'} secondary icon="arrow-right" onPress={p.activeStudy?()=>nav.open({name:'study'}):start}/><Text style={[s.caption,{color:'#E3F2EA'}]}>La selección se adapta a tus intentos y ayudas utilizadas.</Text></View>
 <View style={{gap:12}}><Text style={s.heading}>También puedes…</Text><Action icon="map" title="Entender un cruce" subtitle="Cambia una señal y observa la diferencia" onPress={()=>nav.open({name:'scenes'})}/><Action icon="rotate-ccw" title="Recuperar mis dudas" subtitle={`${marked} guardadas · ${due.length} conceptos con repaso pendiente`} onPress={()=>{if(app.beginStudy('Repaso de dudas',{review:true,count:10}))nav.open({name:'study'});}}/><Action icon="message-circle" title="Resolver una duda" subtitle="Explicación, ejemplo y una nueva oportunidad" onPress={()=>nav.open({name:'tutor'})}/></View>
 {states.some(m=>m.stage==='consolidated')?<Hint>{`${states.filter(m=>m.stage==='consolidated').length} conceptos consolidados con práctica en días distintos.`}</Hint>:<Text style={s.muted}>Los aciertos con dudas también importan. Márcalos para volver a trabajarlos.</Text>}
 <Text style={s.caption}>{pack.notice}</Text></ScrollView>;
}
