import {useState} from 'react';
import {Text,View} from 'react-native';
import {Action,Field,Hint,Page,Source} from '../components/Common';
import {Button} from '../components/UI';
import {useApp} from '../state/Store';
import {useNav} from '../navigation';
import {mastery,stageLabel} from '../engine/learning';
import {colors,styles as s} from '../theme';
export function Learn(){const {pack,progress}=useApp();const nav=useNav();const [search,setSearch]=useState('');const states=new Map(mastery(pack,progress).map(m=>[m.id,m]));const match=search.toLocaleLowerCase();return <Page title="Entiéndelo a tu manera." subtitle="Una idea clara. Un ejemplo. Una situación nueva."><Field label="Buscar un concepto" value={search} onChange={setSearch} placeholder="Cruces, distancia, señales…"/><Action title="Laboratorio de cruces" subtitle="Cinco situaciones conectadas" icon="map" onPress={()=>nav.open({name:'scenes'})}/>{pack.concepts.filter(c=>(c.name+' '+c.topic+' '+c.keywords.join(' ')).toLocaleLowerCase().includes(match)).map(c=><Action key={c.id} title={c.name} subtitle={`${c.topic} · ${stageLabel[states.get(c.id)!.stage]}`} icon="book-open" onPress={()=>nav.open({name:'concept',id:c.id})}/>)}{!pack.concepts.some(c=>(c.name+' '+c.topic+' '+c.keywords.join(' ')).toLocaleLowerCase().includes(match))?<Hint>No encontramos ese concepto. Prueba otra palabra.</Hint>:null}</Page>;}
export function ConceptScreen({id}:{id:string}){const app=useApp(),nav=useNav();const c=app.pack.concepts.find(c=>c.id===id);if(!c)return <Page title="Contenido no disponible" back={nav.back}><Hint>Este concepto ha cambiado. Vuelve al temario.</Hint></Page>;const state=mastery(app.pack,app.progress).find(m=>m.id===id)!;const q=app.pack.questions.find(q=>q.concepts.includes(c.id)&&q.pool==='training'&&q.review!=='retired');return <Page title={c.name} subtitle={stageLabel[state.stage]} back={nav.back}><Hint><Text style={s.heading}>La idea principal</Text><Text style={s.body}>{c.summary}</Text></Hint><View style={s.panel}><Text style={s.heading}>Imagina esta situación</Text><Text style={s.body}>{c.example}</Text></View><View style={[s.panel,{borderColor:'#E9C8A4'}]}><Text style={s.heading}>La confusión habitual</Text><Text style={s.body}>{c.pitfall}</Text></View>{c.prerequisites.length?<View style={{gap:10}}><Text style={s.heading}>Te ayudará repasar</Text>{c.prerequisites.map(id=>{const related=app.pack.concepts.find(c=>c.id===id);return related?<Action key={id} title={related.name} subtitle="Concepto relacionado" icon="corner-up-left" onPress={()=>nav.open({name:'concept',id})}/>:null;})}</View>:null}<Button label="Comprobar si lo entiendo" icon="arrow-right" onPress={()=>{if(app.beginStudy(c.name,{conceptId:id,count:5}))nav.open({name:'study'});}}/><Button label="Explícamelo de otra forma" secondary onPress={()=>nav.open({name:'tutor',question:q})}/><Source url={c.source}/><Text style={s.caption}>Consolidar exige aciertos seguros, sin ayuda, en variantes y días distintos. El tiempo de respuesta no se usa para penalizarte.</Text></Page>;}
