import {useEffect,useState} from 'react';
import {AppState,Text,View} from 'react-native';
import {useVideoPlayer,VideoView} from 'expo-video';
import {Page,Choices,Hint,Source} from '../components/Common';
import {Button} from '../components/UI';
import {useApp} from '../state/Store';
import {useNav} from '../navigation';
import {addAnswer,uid} from '../engine/progress';
import {styles as s} from '../theme';
const clips=[{id:'hidden-pedestrian',name:'Una zona oculta',asset:require('../../assets/risk/hidden-pedestrian.mp4'),start:2.8,end:5.5,concepts:['visibility','vulnerable'],explanation:'La furgoneta limita la visión de la acera. Observa la aparición del peatón y el espacio del que procede; la anticipación empieza antes de que entre en tu trayectoria.'},{id:'braking-car',name:'Una frenada delante',asset:require('../../assets/risk/braking-car.mp4'),start:3,end:5.5,concepts:['gap','attention'],explanation:'Las luces de freno y el cambio de separación son señales para prestar atención. Mantener margen ayuda a responder ante la reducción de velocidad del vehículo que te precede.'}];
export function Risk(){const [index,setIndex]=useState(0);return <RiskClip key={index} index={index} setIndex={setIndex}/>;}
function RiskClip({index,setIndex}:{index:number;setIndex:(i:number)=>void}){const app=useApp(),nav=useNav();const clip=clips[index];const player=useVideoPlayer(clip.asset,p=>{p.loop=false;p.timeUpdateEventInterval=.15;});const [time,setTime]=useState(0);const [playing,setPlaying]=useState(false);const [result,setResult]=useState<{time:number;good:boolean}|null>(null);const [error,setError]=useState('');useEffect(()=>{const t=player.addListener('timeUpdate',e=>setTime(e.currentTime));const p=player.addListener('playingChange',e=>setPlaying(e.isPlaying));const err=player.addListener('statusChange',e=>{if(e.status==='error')setError('No se ha podido reproducir este clip.');});const a=AppState.addEventListener('change',state=>{if(state!=='active')player.pause();});return()=>{t.remove();p.remove();err.remove();a.remove();};},[player]);
 function detect(){if(result)return;const at=player.currentTime;player.pause();const good=at>=clip.start&&at<=clip.end;setResult({time:at,good});const id=uid();app.update(p=>{const next=addAnswer(p,{id,questionId:`risk-${clip.id}`,questionVersion:1,concepts:clip.concepts,family:clip.id,choice:good?0:1,correct:good,at:new Date().toISOString(),elapsedMs:Math.round(at*1000),confidence:'unsure',helpUsed:false,mode:'risk',sessionId:id});return {...next,sessions:[{id,title:`Riesgo: ${clip.name}`,at:new Date().toISOString(),correct:good?1:0,total:1,mode:'risk',unseen:0,elapsedMs:Math.round(at*1000)},...next.sessions]};});}
 return <Page title="Mira un poco más allá." subtitle="Pulsa cuando detectes que la situación requiere atención." back={nav.back}><Choices label="Clip de práctica" value={index} onChange={setIndex} items={clips.map((c,i)=>({value:i,label:c.name}))}/><View style={{borderRadius:14,overflow:'hidden',backgroundColor:'#172A34'}}><VideoView player={player} style={{width:'100%',aspectRatio:16/9}} nativeControls={false}/></View><Text style={s.caption}>Clip animado original · {Math.floor(time)} s · entrenamiento didáctico</Text><Button label={playing?'Pausar vídeo':time>=7.8?'Repetir vídeo':'Reproducir vídeo'} onPress={()=>{if(playing)player.pause();else{if(time>=7.8)player.currentTime=0;player.play();}}}/><Button label="He detectado un riesgo" disabled={!!result||!playing} onPress={detect}/>{result?<><Hint tone={result.good?'green':'orange'}><Text accessibilityLiveRegion="polite" style={s.heading}>{result.good?'Has señalado el tramo previsto.':result.time<clip.start?'Te has adelantado al momento señalado.':'Veamos cuándo empezaba a cambiar.'}</Text><Text style={s.body}>{clip.explanation}</Text><Text style={s.caption}>Tu marca: {result.time.toFixed(1)} s. Tramo anotado: {clip.start}–{clip.end} s. Esta medida no evalúa tu aptitud para conducir.</Text></Hint><Button secondary label="Revisar el momento señalado" onPress={()=>{player.currentTime=clip.start-.5;player.play();}}/><Button secondary label="Practicar otra vez" onPress={()=>{setResult(null);player.currentTime=0;setTime(0);}}/><Button secondary label="Repasar la idea" onPress={()=>nav.open({name:'concept',id:clip.concepts[0]})}/></>:null}{error?<Hint tone="orange">{error}</Hint>:null}<Source url="https://www.dgt.es/muevete-con-seguridad/conviertete-en-un-buen-conductor/test-de-prediccion-de-riesgos/"/><Text style={s.caption}>No son vídeos oficiales ni escenas reales. Los clips incluidos sirven para probar y entrenar la observación en situaciones simplificadas.</Text></Page>;
}
