import {useState} from 'react';
import {Text,View} from 'react-native';
import {Page,Choices,Hint,Source} from '../components/Common';
import {Button} from '../components/UI';
import {TrafficScene} from '../components/TrafficScene';
import {useApp} from '../state/Store';
import {useNav} from '../navigation';
import {styles as s} from '../theme';
export function Scenes(){const app=useApp(),nav=useNav();const [id,setId]=useState(app.pack.scenes[0]?.id);const scene=app.pack.scenes.find(s=>s.id===id);const [reveal,setReveal]=useState(false);if(!scene)return <Page title="Escenas" back={nav.back}><Hint>No hay escenas en este paquete.</Hint></Page>;const question=app.pack.questions.find(q=>q.sceneId===id&&q.review!=='retired');return <Page title="¿Qué cambia aquí?" subtitle="Observa el mismo cruce con señales diferentes." back={nav.back}><Choices label="Situación del cruce" value={id} onChange={id=>{setId(id);setReveal(false);}} items={app.pack.scenes.map((s,i)=>({value:s.id,label:`${i+1}. ${s.rule==='right'?'Sin señales':s.rule==='giveB'?'Ceda en B':s.rule==='giveA'?'Ceda en A':s.rule==='stopA'?'STOP en A':'Bloqueado'}`}))}/><Text style={s.heading}>{scene.name}</Text><TrafficScene key={scene.id} scene={scene} reveal={reveal}/>{!reveal?<Button label="Ver explicación" secondary onPress={()=>setReveal(true)}/>:<Hint><Text style={s.body}>{scene.explanation}</Text><Source url={scene.source}/></Hint>}<Button label="Resolver esta situación" onPress={()=>{if(app.progress.activeStudy){app.setNotice('Tienes otra sesión abierta. Termínala o vuelve a ella antes de iniciar una nueva.');return;}if(question&&app.beginStudy(scene.name,{questions:[question]})){if(reveal)app.patchStudy({helpUsed:true});nav.open({name:'study'});}}}/><Text style={s.muted}>Después prueba a cambiar la señal. Piensa qué detalle modifica la decisión, antes de ver la respuesta.</Text><Button secondary label="Hablar sobre este cruce" onPress={()=>nav.open({name:'tutor',question})}/></Page>;}
