import {useEffect,useState} from 'react';
import {Text,View,Linking} from 'react-native';
import {Page,Field,Hint} from '../components/Common';
import {Button} from '../components/UI';
import {useApp} from '../state/Store';
import {useNav} from '../navigation';
import {api,loadConnection,normalizeServer,saveConnection} from '../services/api';
import {cloudSnapshot,parseProgress} from '../engine/progress';
import type {Connection,ContentPack,Progress} from '../types';
import {styles as s} from '../theme';
export function Settings(){const app=useApp(),nav=useNav();const [date,setDate]=useState(app.progress.settings.examDate);const [url,setUrl]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [connection,setConnection]=useState<Connection|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [shares,setShares]=useState<{id:string;noteId:string;expiresAt:string}[]>([]);useEffect(()=>{loadConnection().then(c=>{setConnection(c);if(c){setUrl(c.url);setEmail(c.email);}});},[]);
 async function run(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function auth(register:boolean){await run(async()=>{const origin=normalizeServer(url);const r=await api<{token:string}>({url:origin,token:''},register?'/api/register':'/api/login',{email,password});const c={url:origin,token:r.token,email};await saveConnection(c);setConnection(c);setPassword('');setMessage('Cuenta conectada. La sincronización se realiza cuando la solicitas.');});}
 function saveDate(){if(date&&(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(date+'T12:00:00'))||new Date(date+'T12:00:00Z').toISOString().slice(0,10)!==date)){setMessage('Escribe una fecha válida con formato AAAA-MM-DD.');return;}app.update(p=>({...p,settings:{...p.settings,examDate:date,updatedAt:new Date().toISOString()}}));setMessage('Fecha objetivo guardada.');}
 return <Page title="Tu plan y tus datos." back={nav.back}><Field label="Fecha objetivo del examen" value={date} onChange={setDate} placeholder="AAAA-MM-DD (opcional)"/><Button label="Guardar fecha objetivo" onPress={saveDate}/><View style={s.panel}><Text style={s.heading}>Contenido descargado</Text><Text style={s.body}>Versión {app.pack.version} · {app.pack.questions.filter(q=>q.review!=='retired').length} ejercicios activos · {app.pack.concepts.length} conceptos</Text><Text style={s.muted}>{app.pack.notice}</Text><Text style={s.caption}>El temario, el progreso, las escenas y los clips incluidos se conservan en el dispositivo. Los servicios conectados necesitan internet.</Text></View><Text style={s.heading}>{connection?'Cuenta conectada':'Conexión opcional'}</Text>{connection?<Text style={s.body}>{connection.email}</Text>:<><Field label="Dirección de tu servidor" value={url} onChange={setUrl} keyboard="url" placeholder="https://tu-servidor.example"/><Field label="Correo de la cuenta" value={email} onChange={setEmail} keyboard="email-address"/><Field label="Contraseña" value={password} onChange={setPassword} secure/><Button label="Entrar" disabled={busy||!email||!password} onPress={()=>auth(false)}/><Button secondary label="Crear cuenta" disabled={busy||!email||password.length<12} onPress={()=>auth(true)}/><Text style={s.caption}>La contraseña debe tener al menos 12 caracteres. La app puede utilizarse sin cuenta.</Text></>}
 {connection?<><Hint>Sincronizar enviará a tu servidor el historial, los marcadores, el plan y las notas del diario. Las sesiones en curso permanecen en este dispositivo.</Hint><Button label={busy?'Procesando…':'Sincronizar mi progreso y mis notas'} disabled={busy} onPress={()=>run(async()=>{await app.flush();const r=await api<{progress:Progress}>(connection,'/api/sync',{progress:cloudSnapshot(app.progress)});app.merge(parseProgress(JSON.stringify(r.progress),app.pack));setMessage('Progreso sincronizado y combinado con los cambios de otros dispositivos.');})}/><Button secondary label="Buscar actualización del contenido" disabled={busy} onPress={()=>run(async()=>{const p=await api<ContentPack>(connection,'/api/content');const changed=await app.updatePack(p);setMessage(changed?'Contenido actualizado.':'Ya tienes la última versión disponible en este servidor.');})}/><Button secondary label="Ver mis enlaces compartidos" disabled={busy} onPress={()=>run(async()=>{const r=await api<{shares:typeof shares}>(connection,'/api/shares');setShares(r.shares);setMessage(r.shares.length?'Puedes revocar cada enlace aquí.':'No tienes enlaces activos.');})}/>{shares.map(share=><View key={share.id} style={s.panel}><Text style={s.muted}>Nota: {app.progress.notes.find(n=>n.id===share.noteId)?.text.slice(0,70)??share.noteId}</Text><Text style={s.caption}>Caduca: {new Date(share.expiresAt).toLocaleDateString('es-ES')}</Text><Button label="Revocar este enlace" secondary disabled={busy} onPress={()=>run(async()=>{await api(connection,'/api/shares/revoke',{id:share.id});setShares(s=>s.filter(x=>x.id!==share.id));setMessage('Enlace revocado.');})}/></View>)}<Button secondary label="Cerrar sesión de la cuenta" disabled={busy} onPress={()=>run(async()=>{await api(connection,'/api/logout',{});await saveConnection(null);setConnection(null);setShares([]);setMessage('Cuenta desconectada. El progreso local se conserva.');})}/></>:null}{message?<Hint>{message}</Hint>:null}<Text style={s.caption}>El acceso al tutor conversacional se configura en el servidor. La clave del proveedor nunca se guarda en la aplicación móvil.</Text></Page>;
}
