import {useEffect,useRef} from 'react';
import {Pressable,ScrollView,Text,View} from 'react-native';
import {Button,Icon,Meter} from '../components/UI';
import {Choices,Hint,Source} from '../components/Common';
import {ReportQuestion} from '../components/ReportQuestion';
import {TrafficScene} from '../components/TrafficScene';
import {useApp} from '../state/Store';
import {useNav} from '../navigation';
import {colors,styles as s} from '../theme';
export function Study(){const app=useApp(),nav=useNav();const a=app.progress.activeStudy;const scroll=useRef<ScrollView>(null);useEffect(()=>{scroll.current?.scrollTo({y:0,animated:false});},[a?.index]);if(!a)return <View style={s.content}><Hint>La sesión ha terminado o el contenido ha cambiado.</Hint><Button label="Volver al inicio" onPress={nav.home}/></View>;
 const q=a.questions[a.index];const scene=app.pack.scenes.find(s=>s.id===q.sceneId);const marked=app.progress.bookmarks.find(b=>b.questionId===q.id)?.active;
 return <View style={{flex:1}}><View style={[s.between,{paddingHorizontal:22,paddingVertical:8,borderBottomWidth:1,borderColor:colors.border}]}><Pressable accessibilityRole="button" accessibilityLabel="Salir de la sesión" style={[s.row,{minHeight:44}]} onPress={nav.back}><Icon name="chevron-left"/><Text style={s.body}>Salir</Text></Pressable><Text style={[s.muted,{flexShrink:1}]}>{a.title}</Text></View><ScrollView ref={scroll} contentContainerStyle={[s.content,{gap:20}]}><View style={s.row}><Text style={s.muted}>{a.index+1} de {a.questions.length}</Text><Meter value={(a.index+1)/a.questions.length} label="Avance"/></View><Text style={s.badge}>{q.topic}</Text><Text accessibilityRole="header" style={[s.heading,{fontSize:25,lineHeight:33}]}>{q.prompt}</Text>{scene?<TrafficScene scene={scene} reveal={a.checked}/>:null}<View accessibilityRole="radiogroup" style={{gap:12}}>{q.options.map((option,i)=>{const correct=a.checked&&i===q.correct;const wrong=a.checked&&a.selected===i&&!correct;return <Pressable key={i} testID={`answer-${i}`} accessibilityRole="radio" accessibilityLabel={option} accessibilityState={{checked:a.selected===i,disabled:a.checked}} disabled={a.checked} onPress={()=>app.patchStudy({selected:i})} style={{minHeight:72,padding:16,borderRadius:12,borderWidth:2,borderColor:correct?colors.green:wrong?colors.red:a.selected===i?colors.green:colors.border,backgroundColor:correct?colors.mint:wrong?colors.orangeLight:colors.surface,flexDirection:'row',gap:14,alignItems:'center'}}><Text style={[s.body,{fontWeight:'700'}]}>{String.fromCharCode(65+i)}</Text><Text style={[s.body,{flex:1}]}>{option}</Text>{correct?<Icon name="check" color={colors.green}/>:wrong?<Icon name="x" color={colors.red}/>:null}</Pressable>;})}</View>
 {!a.checked?<><Text style={s.body}>¿Cómo has llegado a tu respuesta?</Text><Choices label="Confianza en mi respuesta" value={a.confidence} onChange={confidence=>app.patchStudy({confidence})} items={[{value:'sure',label:'Lo entiendo'},{value:'unsure',label:'Tengo dudas'},{value:'guess',label:'Estoy probando'}]}/><Button label="Comprobar" disabled={a.selected===null} onPress={app.checkStudy}/><Button label="Necesito una explicación" secondary onPress={()=>{app.patchStudy({helpUsed:true});nav.open({name:'tutor',question:q});}}/></>:<><Hint tone={a.selected===q.correct?'green':'orange'}><Text accessibilityLiveRegion="polite" style={s.heading}>{a.selected===q.correct?'¡Bien! Vamos a afianzarlo.':'Vamos a entenderlo.'}</Text><Text style={s.body}>{q.explanation}</Text>{a.confidence!=='sure'||a.helpUsed?<Text style={s.muted}>Esta idea seguirá en práctica porque hubo dudas o ayuda.</Text>:null}<Source url={q.source}/></Hint><Button label={a.index===a.questions.length-1?'Ver resultado':'Siguiente pregunta'} onPress={()=>{if(a.index===a.questions.length-1){const result=app.completeStudy();if(result)nav.replace({name:'result',result});}else app.nextStudy();}}/><Button secondary label="Quiero entender el porqué" onPress={()=>nav.open({name:'tutor',question:q})}/></>}
 <Pressable accessibilityRole="button" accessibilityLabel={marked?'Quitar de mis dudas':'Guardar como duda'} onPress={()=>app.bookmark(q)} style={[s.row,{minHeight:44}]}><Icon name="bookmark" color={marked?colors.green:colors.muted}/><Text style={s.body}>{marked?'Quitar de mis dudas':'Guardar como duda'}</Text></Pressable><ReportQuestion key={q.id} questionId={q.id}/><Text style={s.caption}>Ejercicio original de práctica · {q.review==='reviewed'?`Revisión: ${q.reviewedBy}`:'Pendiente de revisión profesional'}</Text></ScrollView></View>;
}
