import {useEffect,useState} from 'react';
import {Image,Text,View} from 'react-native';
import * as Speech from 'expo-speech';
import * as ImagePicker from 'expo-image-picker';
import {Page,Field,Choices,Hint,Source} from '../components/Common';
import {Button} from '../components/UI';
import {VoiceInput} from '../components/VoiceInput';
import {useApp} from '../state/Store';
import {useNav} from '../navigation';
import {guidedReply,type TutorMessage} from '../services/tutor';
import {api,loadConnection} from '../services/api';
import {styles as s} from '../theme';
import type {Question} from '../types';
export function Tutor({question:q}:{question?:Question}){const app=useApp(),nav=useNav();const [input,setInput]=useState('');const [mode,setMode]=useState<'guided'|'ai'>('guided');const [available,setAvailable]=useState(false);const [messages,setMessages]=useState<TutorMessage[]>(()=>[{role:'assistant',provider:'guided',...guidedReply(app.pack,q?.prompt??'',q)}]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [attachment,setAttachment]=useState<{uri:string;base64:string;mime:string}|null>(null);const [ocr,setOcr]=useState('');
 useEffect(()=>{loadConnection().then(c=>c?api<{ai:boolean}>(c,'/api/health'):null).then(r=>setAvailable(!!r?.ai)).catch(()=>{});return()=>{Speech.stop();};},[]);
 async function send(kind:'explain'|'simple'|'reason'='explain'){const text=input.trim()|| (kind==='simple'?'Explícamelo con un ejemplo más sencillo.':kind==='reason'?'Quiero contrastar mi razonamiento.':'Explícame esta situación.');setError('');if(mode==='guided'){const reply=guidedReply(app.pack,text,q,kind);setMessages(m=>[...m,{role:'user',text},{role:'assistant',provider:mode,...reply}]);setInput('');return;}setBusy(true);try{const c=await loadConnection();if(!c)throw Error('Conecta una cuenta en Mi avance.');const reply=await api<{text:string;source?:string}>(c,'/api/tutor',{questionId:q?.id,text,messages:messages.slice(-6),kind});setMessages(m=>[...m,{role:'user',text},{role:'assistant',provider:mode,...reply}]);setInput('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function pick(){try{const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],base64:true,quality:.65,allowsEditing:true});if(!r.canceled&&r.assets[0].base64){setAttachment({uri:r.assets[0].uri,base64:r.assets[0].base64,mime:r.assets[0].mimeType??'image/jpeg'});setOcr('');}}catch(e){setError((e as Error).message);}}
 async function readImage(){if(!attachment)return;setBusy(true);try{const c=await loadConnection();if(!c)throw Error('Conecta una cuenta para leer imágenes.');const r=await api<{text:string}>(c,'/api/ocr',{image:attachment.base64,mime:attachment.mime});setOcr(r.text);setAttachment(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Page title="Vamos a entenderlo." subtitle={q?'Trabajamos sobre tu pregunta.':'Escribe una duda o elige un concepto.'} back={nav.back}>{q?<Hint>{q.prompt}</Hint>:null}<Choices label="Tipo de ayuda" value={mode} onChange={setMode} items={[{value:'guided',label:'Guía local'},{value:'ai',label:'Tutor conversacional'}]}/>{mode==='guided'?<Text style={s.caption}>Explicaciones preescritas y búsqueda por conceptos. Funciona sin conexión; no interpreta libremente tu razonamiento.</Text>:<Hint tone={available?'green':'orange'}>{available?'El mensaje y el contexto de la pregunta se enviarán a tu servidor y su proveedor.':'El tutor conversacional necesita un servidor con proveedor configurado. Puedes seguir con la guía local.'}</Hint>}{messages.slice(-8).map((m,i)=><View key={i} style={[s.panel,{backgroundColor:m.role==='user'?'#E3F2EA':'#FFF'}]}><Text style={s.badge}>{m.role==='user'?'Tú':m.provider!=='ai'?'Guía':'Tutor'}</Text><Text style={s.body}>{m.text}</Text>{m.source?<Source url={m.source}/>:null}{m.role==='assistant'?<Button secondary label="Escuchar explicación" icon="volume-2" onPress={()=>{Speech.stop();Speech.speak(m.text,{language:'es-ES',onError:()=>setError('No se ha podido reproducir la voz del dispositivo.')});}}/>:null}</View>)}<Button secondary label="Detener lectura" onPress={()=>Speech.stop()}/><Field label="Tu duda o razonamiento" value={input} onChange={setInput} multiline placeholder="Pensaba que el coche de la derecha siempre pasaba…"/><VoiceInput onText={setInput}/><Button label={busy?'Preparando explicación…':'Enviar duda'} disabled={busy||(mode==='ai'&&!available)} onPress={()=>send()}/><Button secondary label="Un ejemplo más sencillo" disabled={busy||(mode==='ai'&&!available)} onPress={()=>send('simple')}/><Button secondary label="Contrastar mi razonamiento" disabled={busy||(mode==='ai'&&!available)} onPress={()=>send('reason')}/><Button secondary label="Subir una captura" icon="image" disabled={!available||busy} onPress={pick}/>{attachment?<View style={s.panel}><Image source={{uri:attachment.uri}} style={{height:180,width:'100%'}} resizeMode="contain"/><Text style={s.caption}>Revisa la imagen. Se enviará al servidor y al proveedor solo al pulsar el botón siguiente.</Text><Button label="Enviar imagen para leerla" disabled={busy} onPress={readImage}/><Button label="Descartar imagen" secondary onPress={()=>setAttachment(null)}/></View>:null}{ocr?<View style={s.panel}><Field label="Confirma el texto reconocido" value={ocr} onChange={setOcr} multiline/><Button label="Usar este texto en mi duda" onPress={()=>{setInput(ocr);setOcr('');setMode('ai');}}/></View>:null}{error?<Hint tone="orange">{error}</Hint>:null}{q?<Button label="Practicar el concepto" secondary onPress={()=>nav.open({name:'concept',id:q.concepts[0]})}/>:null}<Text style={s.caption}>Las explicaciones se apoyan en el contenido disponible. Contrasta las dudas importantes con tu profesor; el banco sigue en revisión.</Text></Page>;
}
