import type {Progress,Answer,ContentPack} from '../types';
export const uid=()=>`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,12)}`;
export const emptyProgress=():Progress=>({version:2,answers:[],sessions:[],notes:[],bookmarks:[],settings:{minutes:5,examDate:'',updatedAt:new Date(0).toISOString()},activeStudy:null,activeExam:null});
const date=(x:unknown)=>typeof x==='string'&&Number.isFinite(Date.parse(x));
export function parseProgress(raw:string|null,pack?:ContentPack):Progress{
 if(raw===null)return emptyProgress();const p=JSON.parse(raw);
 if(p.version===1){if(!Array.isArray(p.answers)||!Array.isArray(p.sessions))throw new Error('Invalid legacy data');const base=emptyProgress();base.answers=p.answers.map((a:any,i:number)=>{if(typeof a.questionId!=='string'||typeof a.correct!=='boolean'||!date(a.at)||!Number.isInteger(a.choice)||a.choice<0||a.choice>2)throw new Error('Invalid legacy answer');const q=pack?.questions.find(q=>q.id===a.questionId);return {...a,id:`legacy-${i}-${a.at}`,questionVersion:q?.version??1,concepts:q?.concepts??[],family:q?.family??a.questionId,elapsedMs:0,confidence:'unsure',helpUsed:false,mode:'study',sessionId:'legacy'};});base.sessions=p.sessions.map((s:any)=>({...s,mode:'study',elapsedMs:0,unseen:0}));return base;}
 if(p.version!==2||!Array.isArray(p.answers)||!Array.isArray(p.sessions)||!Array.isArray(p.notes)||!Array.isArray(p.bookmarks)||![5,10,20].includes(p.settings?.minutes)||!date(p.settings.updatedAt)||typeof p.settings.examDate!=='string')throw new Error('Invalid data');
 for(const a of p.answers)if(typeof a.id!=='string'||typeof a.questionId!=='string'||!Array.isArray(a.concepts)||!a.concepts.every((x:unknown)=>typeof x==='string')||!Number.isInteger(a.choice)||a.choice<0||a.choice>2||typeof a.correct!=='boolean'||!date(a.at)||!['sure','unsure','guess'].includes(a.confidence)||!['study','exam','scene','risk'].includes(a.mode)||!Number.isFinite(a.elapsedMs)||a.elapsedMs<0||!Number.isInteger(a.questionVersion)||typeof a.helpUsed!=='boolean'||typeof a.family!=='string'||typeof a.sessionId!=='string')throw new Error('Invalid answer');
 for(const s of p.sessions)if(typeof s.id!=='string'||typeof s.title!=='string'||!date(s.at)||!Number.isInteger(s.total)||s.total<1||!Number.isInteger(s.correct)||s.correct<0||s.correct>s.total)throw new Error('Invalid session');
 for(const n of p.notes)if(typeof n.id!=='string'||typeof n.text!=='string'||n.text.length>6000||!Array.isArray(n.concepts)||!n.concepts.every((x:unknown)=>typeof x==='string')||!date(n.at)||!date(n.updatedAt)||typeof n.deleted!=='boolean')throw new Error('Invalid note');
 for(const b of p.bookmarks)if(typeof b.questionId!=='string'||typeof b.active!=='boolean'||!date(b.updatedAt))throw new Error('Invalid bookmark');
 // Never trust remote active-session snapshots: synchronization explicitly removes them.
 if(p.activeStudy&&(!Array.isArray(p.activeStudy.questions)||!Array.isArray(p.activeStudy.answers)||p.activeStudy.index<0||p.activeStudy.index>=p.activeStudy.questions.length))throw new Error('Invalid active study');
 if(p.activeExam&&(!Array.isArray(p.activeExam.questions)||!date(p.activeExam.deadline)||p.activeExam.index<0||p.activeExam.index>=p.activeExam.questions.length))throw new Error('Invalid active exam');
 return p;
}
function mergeBy<T>(a:T[],b:T[],key:(v:T)=>string,newer?:(v:T)=>string):T[]{const m=new Map<string,T>();for(const v of [...a,...b]){const prior=m.get(key(v));if(!prior||!newer||newer(v)>newer(prior)||(newer(v)===newer(prior)&&JSON.stringify(v)>JSON.stringify(prior)))m.set(key(v),v);}return [...m.values()];}
export function mergeProgress(local:Progress,remote:Progress):Progress{return {...local,answers:mergeBy(local.answers,remote.answers,a=>a.id).sort((a,b)=>a.at.localeCompare(b.at)||a.id.localeCompare(b.id)),sessions:mergeBy(local.sessions,remote.sessions,s=>s.id).sort((a,b)=>b.at.localeCompare(a.at)),notes:mergeBy(local.notes,remote.notes,n=>n.id,n=>n.updatedAt),bookmarks:mergeBy(local.bookmarks,remote.bookmarks,b=>b.questionId,b=>b.updatedAt),settings:remote.settings.updatedAt>local.settings.updatedAt?remote.settings:local.settings};}
export function cloudSnapshot(p:Progress):Progress{return {...p,activeStudy:null,activeExam:null};}
export function addAnswer(p:Progress,a:Answer):Progress{return p.answers.some(x=>x.id===a.id)?p:{...p,answers:[...p.answers,a]};}
