import {createServer,type IncomingMessage,type ServerResponse} from 'node:http';
import {DatabaseSync} from 'node:sqlite';
import {createHash,randomBytes,scryptSync,timingSafeEqual,randomUUID} from 'node:crypto';
import {readFileSync,mkdirSync} from 'node:fs';
import {dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {initialPack} from '../src/data/catalog.ts';
import {validatePack,validateQuestion} from '../src/engine/content.ts';
import {cloudSnapshot,emptyProgress,mergeProgress,parseProgress} from '../src/engine/progress.ts';
import type {ContentPack,Question,Scene} from '../src/types.ts';
import {providerOCR,providerReply,providerTranscribe} from './provider.ts';
export type Config={dbPath:string;adminEmail?:string;adminPassword?:string;publicUrl?:string;origins?:string[];apiKey?:string;model?:string;allowRegistration?:boolean};
class HttpError extends Error{status:number;constructor(status:number,message:string){super(message);this.status=status;}}
const hash=(v:string)=>createHash('sha256').update(v).digest('hex');
function passwordHash(password:string){const salt=randomBytes(16).toString('hex');return salt+':'+scryptSync(password,salt,64).toString('hex');}
function validPassword(password:string,stored:string){const [salt,h]=stored.split(':');const b=scryptSync(password,salt,64);return timingSafeEqual(b,Buffer.from(h,'hex'));}
async function body(req:IncomingMessage){const chunks:Buffer[]=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>10*1024*1024)throw new HttpError(413,'El archivo o los datos superan el límite de 10 MB.');chunks.push(chunk);}try{return JSON.parse(Buffer.concat(chunks).toString()||'{}');}catch{throw new HttpError(400,'JSON inválido.');}}
function text(value:unknown,max=6000){if(typeof value!=='string'||!value.trim()||value.length>max)throw new HttpError(400,'Texto vacío o demasiado largo.');return value.trim();}
function json(res:ServerResponse,data:unknown,status=200){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
export function createApp(config:Config){
 if(config.dbPath!==':memory:')mkdirSync(dirname(config.dbPath),{recursive:true});const db=new DatabaseSync(config.dbPath);db.exec('PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;');
 db.exec(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,password TEXT NOT NULL,role TEXT NOT NULL);CREATE TABLE IF NOT EXISTS tokens(hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),expires INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS progress(user_id TEXT PRIMARY KEY REFERENCES users(id),json TEXT NOT NULL);CREATE TABLE IF NOT EXISTS packs(version INTEGER PRIMARY KEY,json TEXT NOT NULL,at TEXT NOT NULL,author TEXT NOT NULL);CREATE TABLE IF NOT EXISTS drafts(id TEXT PRIMARY KEY,kind TEXT NOT NULL,json TEXT NOT NULL,base_version INTEGER NOT NULL,author TEXT NOT NULL);CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY AUTOINCREMENT,at TEXT NOT NULL,actor TEXT NOT NULL,action TEXT NOT NULL,target TEXT NOT NULL);CREATE TABLE IF NOT EXISTS shares(id TEXT PRIMARY KEY,hash TEXT UNIQUE NOT NULL,user_id TEXT NOT NULL,note_id TEXT NOT NULL,text TEXT NOT NULL,expires INTEGER NOT NULL,revoked INTEGER NOT NULL DEFAULT 0,feedback TEXT NOT NULL DEFAULT '');CREATE TABLE IF NOT EXISTS reports(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,question_id TEXT NOT NULL,text TEXT NOT NULL,at TEXT NOT NULL,resolved INTEGER NOT NULL DEFAULT 0);`);
 if(!db.prepare('SELECT version FROM packs LIMIT 1').get())db.prepare('INSERT INTO packs VALUES(?,?,?,?)').run(initialPack.version,JSON.stringify(initialPack),initialPack.updatedAt,'bootstrap');
 if(config.adminEmail&&config.adminPassword){if(config.adminPassword.length<12)throw Error('La contraseña editorial debe tener al menos 12 caracteres.');const email=config.adminEmail.toLowerCase().trim();if(!db.prepare('SELECT id FROM users WHERE email=?').get(email))db.prepare('INSERT INTO users VALUES(?,?,?,?)').run(randomUUID(),email,passwordHash(config.adminPassword),'admin');}
 const current=():ContentPack=>JSON.parse((db.prepare('SELECT json FROM packs ORDER BY version DESC LIMIT 1').get() as any).json);
 const log=(actor:string,action:string,target:string)=>db.prepare('INSERT INTO audit(at,actor,action,target) VALUES(?,?,?,?)').run(new Date().toISOString(),actor,action,target);
 const limits=new Map<string,{count:number;until:number}>();const throttle=(key:string,max:number,window=60000)=>{const now=Date.now();let entry=limits.get(key);if(!entry||entry.until<now){entry={count:0,until:now+window};limits.set(key,entry);}if(++entry.count>max)throw new HttpError(429,'Demasiadas solicitudes. Espera un momento.');if(limits.size>10000)for(const [k,v] of limits)if(v.until<now)limits.delete(k);};
 const auth=(req:IncomingMessage,admin=false)=>{const bearer=req.headers.authorization?.match(/^Bearer ([A-Za-z0-9_-]+)$/)?.[1];if(!bearer)throw new HttpError(401,'Inicia sesión para continuar.');const row=db.prepare('SELECT u.* FROM users u JOIN tokens t ON t.user_id=u.id WHERE t.hash=? AND t.expires>?').get(hash(bearer),Date.now()) as any;if(!row)throw new HttpError(401,'La sesión ha caducado. Vuelve a entrar.');if(admin&&row.role!=='admin')throw new HttpError(403,'No tienes acceso editorial.');return row;};
 const token=(user:any)=>{const value=randomBytes(32).toString('base64url');db.prepare('INSERT INTO tokens VALUES(?,?,?)').run(hash(value),user.id,Date.now()+30*86400000);return value;};
 const server=createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Frame-Options','DENY');try{
  const url=new URL(req.url??'/','http://localhost');const path=url.pathname;const origin=req.headers.origin;const allowed=config.origins??[];if(origin){if(!allowed.includes(origin)){throw new HttpError(403,'Origen web no autorizado. Configura ALLOWED_ORIGINS en el servidor.');}res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Headers','Authorization, Content-Type');res.setHeader('Access-Control-Allow-Methods','GET, POST, OPTIONS');}if(req.method==='OPTIONS'){res.writeHead(204);res.end();return;}
  throttle(req.socket.remoteAddress??'unknown',180);
  if(req.method==='GET'&&(path==='/admin'||path==='/admin.js'||path==='/admin.css'||path==='/review'||path==='/review.js')){const file=path==='/admin'?'admin.html':path==='/review'?'review.html':path.slice(1);res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'");res.writeHead(200,{'Content-Type':file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html; charset=utf-8'});res.end(readFileSync(join(dirname(fileURLToPath(import.meta.url)),'public',file)));return;}
  if(path==='/api/health'&&req.method==='GET'){json(res,{ok:true,contentVersion:current().version,ai:!!config.apiKey,registration:config.allowRegistration!==false});return;}
  if(path==='/api/content'&&req.method==='GET'){json(res,current());return;}
  if((path==='/api/login'||path==='/api/register')&&req.method==='POST'){
   throttle('auth:'+(req.socket.remoteAddress??''),12,60000);const b=await body(req);const email=text(b.email,254).toLowerCase();const password=text(b.password,256);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new HttpError(400,'Correo inválido.');let user=db.prepare('SELECT * FROM users WHERE email=?').get(email) as any;
   if(path==='/api/register'){if(config.allowRegistration===false)throw new HttpError(403,'El registro no está habilitado.');if(password.length<12)throw new HttpError(400,'Utiliza al menos 12 caracteres.');if(user)throw new HttpError(409,'No se pudo crear esta cuenta. Prueba a iniciar sesión.');const id=randomUUID();db.prepare('INSERT INTO users VALUES(?,?,?,?)').run(id,email,passwordHash(password),'student');user={id,email,role:'student'};log(id,'register',id);}else if(!user||!validPassword(password,user.password))throw new HttpError(401,'Credenciales incorrectas.');json(res,{token:token(user),role:user.role,email:user.email});return;
  }
  if(path==='/api/logout'&&req.method==='POST'){auth(req);db.prepare('DELETE FROM tokens WHERE hash=?').run(hash(req.headers.authorization!.slice(7)));json(res,{ok:true});return;}
  if(path==='/api/sync'&&req.method==='POST'){
   const user=auth(req),b=await body(req);let remote;try{remote=parseProgress(JSON.stringify({...b.progress,activeStudy:null,activeExam:null}),current());}catch{throw new HttpError(400,'Formato de progreso inválido.');}const row=db.prepare('SELECT json FROM progress WHERE user_id=?').get(user.id) as any;const saved=row?parseProgress(row.json,current()):emptyProgress();const merged=cloudSnapshot(mergeProgress(saved,remote));db.prepare('INSERT INTO progress VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET json=excluded.json').run(user.id,JSON.stringify(merged));json(res,{progress:merged});return;
  }
  if(path==='/api/shares'&&req.method==='POST'){
   const user=auth(req),b=await body(req);const id=randomUUID(),secret=randomBytes(24).toString('base64url');const base=config.publicUrl;if(!base)throw new HttpError(503,'Configura PUBLIC_URL para crear enlaces que tu profesor pueda abrir.');db.prepare('INSERT INTO shares(id,hash,user_id,note_id,text,expires) VALUES(?,?,?,?,?,?)').run(id,hash(secret),user.id,text(b.noteId,120),text(b.text),Date.now()+7*86400000);log(user.id,'share.create',id);json(res,{id,url:base.replace(/\/$/,'')+'/review#'+secret});return;
  }
  if(path==='/api/shares'&&req.method==='GET'){const user=auth(req);const shares=(db.prepare('SELECT id,note_id,expires FROM shares WHERE user_id=? AND revoked=0 AND expires>?').all(user.id,Date.now()) as any[]).map(s=>({id:s.id,noteId:s.note_id,expiresAt:new Date(s.expires).toISOString()}));json(res,{shares});return;}
  if(path==='/api/shares/revoke'&&req.method==='POST'){const user=auth(req),b=await body(req);db.prepare('UPDATE shares SET revoked=1 WHERE id=? AND user_id=?').run(text(b.id,120),user.id);log(user.id,'share.revoke',b.id);json(res,{ok:true});return;}
  if(path==='/api/review'&&req.method==='POST'){const b=await body(req);const share=db.prepare('SELECT id,text,feedback FROM shares WHERE hash=? AND revoked=0 AND expires>?').get(hash(text(b.secret,100)),Date.now()) as any;if(!share)throw new HttpError(404,'El enlace no está disponible o ha caducado.');if(b.feedback!==undefined){db.prepare('UPDATE shares SET feedback=? WHERE id=?').run(text(b.feedback,4000),share.id);json(res,{ok:true});}else json(res,{text:share.text,feedback:share.feedback});return;}
  if(path==='/api/feedback'&&req.method==='GET'){const user=auth(req);const row=db.prepare('SELECT feedback FROM shares WHERE user_id=? AND note_id=? AND revoked=0 ORDER BY expires DESC LIMIT 1').get(user.id,text(url.searchParams.get('noteId'),120)) as any;json(res,{feedback:row?.feedback??''});return;}
  if(path==='/api/report'&&req.method==='POST'){const user=auth(req),b=await body(req);if(!current().questions.some(q=>q.id===b.questionId))throw new HttpError(404,'Pregunta no encontrada.');db.prepare('INSERT INTO reports VALUES(?,?,?,?,?,0)').run(randomUUID(),user.id,b.questionId,text(b.text,2000),new Date().toISOString());json(res,{ok:true});return;}
  if(['/api/tutor','/api/ocr','/api/transcribe'].includes(path)&&req.method==='POST'){
   const user=auth(req);throttle('ai:'+user.id,15,3600000);if(!config.apiKey)throw new HttpError(503,'El proveedor de IA aún no está configurado. La guía local sigue disponible.');const b=await body(req);if(path==='/api/tutor'){json(res,await providerReply(config,current(),b));return;}if(path==='/api/ocr'){if(!['image/jpeg','image/png','image/webp'].includes(b.mime)||typeof b.image!=='string'||b.image.length>8*1024*1024)throw new HttpError(400,'Imagen no admitida.');json(res,await providerOCR(config,b.image,b.mime));return;}if(!['audio/webm','audio/mp4'].includes(b.mime)||typeof b.audio!=='string'||b.audio.length>8*1024*1024)throw new HttpError(400,'Audio no admitido.');json(res,await providerTranscribe(config,b.audio,b.mime));return;
  }
  if(path.startsWith('/api/admin')){
   const user=auth(req,true);
   if(path==='/api/admin/state'&&req.method==='GET'){json(res,{pack:current(),drafts:db.prepare('SELECT * FROM drafts').all(),history:db.prepare('SELECT version,at,author FROM packs ORDER BY version DESC LIMIT 20').all(),audit:db.prepare('SELECT * FROM audit ORDER BY id DESC LIMIT 40').all(),reports:db.prepare('SELECT * FROM reports WHERE resolved=0 ORDER BY at DESC').all()});return;}
   const b=await body(req);
   if(path==='/api/admin/draft'&&req.method==='POST'){
    const pack=current();if(b.baseVersion!==pack.version)throw new HttpError(409,'El contenido cambió. Recarga antes de editar.');const kind=['scene','concept'].includes(b.kind)?b.kind:'question';const item=b.item;
    try{if(kind==='question')validateQuestion(item,pack);else if(kind==='scene')validatePack({...pack,scenes:[...pack.scenes.filter(s=>s.id!==item?.id),item]});else validatePack({...pack,concepts:[...pack.concepts.filter(c=>c.id!==item?.id),item]});}catch(e){throw new HttpError(400,(e as Error).message);}
    const id=text(item.id,120);db.prepare('INSERT INTO drafts VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET kind=excluded.kind,json=excluded.json,base_version=excluded.base_version,author=excluded.author').run(id,kind,JSON.stringify(item),pack.version,user.email);log(user.email,'draft.save',id);json(res,{ok:true,id});return;
   }
   if(path==='/api/admin/publish'&&req.method==='POST'){
    const draft=db.prepare('SELECT * FROM drafts WHERE id=?').get(text(b.id,120)) as any;if(!draft)throw new HttpError(404,'No existe el borrador.');const pack=current();if(b.baseVersion!==pack.version||draft.base_version!==pack.version)throw new HttpError(409,'Hay una versión posterior. Revisa el borrador antes de publicar.');const item=JSON.parse(draft.json);const now=new Date().toISOString();let next:ContentPack={...pack,version:pack.version+1,updatedAt:now};
    if(draft.kind==='question'){const previous=pack.questions.find(q=>q.id===item.id);const q:Question={...item,version:(previous?.version??0)+1};if(q.review==='reviewed'){q.reviewedBy=user.email;q.reviewedAt=now;}next.questions=[...pack.questions.filter(q=>q.id!==item.id),q];}else if(draft.kind==='concept'){next.concepts=[...pack.concepts.filter(c=>c.id!==item.id),item];next.questions=pack.questions.map(q=>q.concepts.includes(item.id)?{...q,version:q.version+1,review:'demonstration',reviewedBy:null,reviewedAt:null}:q);}else{next.scenes=[...pack.scenes.filter(s=>s.id!==item.id),item];next.questions=pack.questions.map(q=>q.sceneId===item.id?{...q,version:q.version+1,correct:item.winner==='A'?0:item.winner==='B'?1:2,explanation:item.explanation,review:'demonstration',reviewedAt:null,reviewedBy:null}:q);if(!next.questions.some(q=>q.sceneId===item.id)){next.questions.push({id:'scene-'+item.id,topic:'Cruces y prioridades',prompt:item.name+': ambos coches van recto. ¿Quién debe pasar primero?',options:['El coche A.','El coche B.','Ninguno debe entrar todavía.'],correct:item.winner==='A'?0:item.winner==='B'?1:2,explanation:item.explanation,source:item.source,concepts:item.concepts,family:item.id,version:1,pool:'training',sceneId:item.id,review:'demonstration',reviewedBy:null,reviewedAt:null,rights:'Escena original del editor; revisión pendiente.'});}}
    try{validatePack(next);}catch(e){throw new HttpError(400,(e as Error).message);}db.exec('BEGIN IMMEDIATE');try{db.prepare('INSERT INTO packs VALUES(?,?,?,?)').run(next.version,JSON.stringify(next),now,user.email);db.prepare('DELETE FROM drafts WHERE id=?').run(item.id);log(user.email,'content.publish',item.id);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}json(res,{ok:true,version:next.version});return;
   }
   if(path==='/api/admin/restore'&&req.method==='POST'){
    const pack=current();if(b.baseVersion!==pack.version)throw new HttpError(409,'La versión actual ha cambiado.');const row=db.prepare('SELECT json FROM packs WHERE version=?').get(Number(b.version)) as any;if(!row)throw new HttpError(404,'Versión no encontrada.');const old:ContentPack=JSON.parse(row.json);const next={...old,version:pack.version+1,updatedAt:new Date().toISOString(),questions:old.questions.map(q=>({...q,version:(pack.questions.find(p=>p.id===q.id)?.version??q.version)+1}))};validatePack(next);db.prepare('INSERT INTO packs VALUES(?,?,?,?)').run(next.version,JSON.stringify(next),next.updatedAt,user.email);log(user.email,'content.restore',String(b.version));json(res,{ok:true,version:next.version});return;
   }
   if(path==='/api/admin/resolve'&&req.method==='POST'){db.prepare('UPDATE reports SET resolved=1 WHERE id=?').run(text(b.id,120));log(user.email,'report.resolve',b.id);json(res,{ok:true});return;}
  }
  throw new HttpError(404,'Ruta no encontrada.');
 }catch(e){json(res,{error:e instanceof HttpError?e.message:'No se pudo completar la operación.'},e instanceof HttpError?e.status:500);}});
 return {server,db,current};
}
