import type {ReactNode} from 'react';
import {Linking,Pressable,ScrollView,Text,TextInput,View,KeyboardAvoidingView,Platform} from 'react-native';
import {Icon,type IconName} from './UI';
import {colors,styles as s} from '../theme';
export function Page({title,subtitle,back,children}:{title:string;subtitle?:string;back?:()=>void;children:ReactNode}){return <KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.content}>{back?<Pressable accessibilityRole="button" accessibilityLabel="Volver" onPress={back} style={[s.row,{minHeight:44}]}><Icon name="chevron-left"/><Text style={s.body}>Volver</Text></Pressable>:null}<View style={{gap:8}}><Text accessibilityRole="header" style={s.title}>{title}</Text>{subtitle?<Text style={[s.body,{color:colors.muted}]}>{subtitle}</Text>:null}</View>{children}</ScrollView></KeyboardAvoidingView>;}
export function Choices<T extends string|number>({items,value,onChange,label}:{items:{value:T;label:string}[];value:T;onChange:(v:T)=>void;label:string}){return <View accessibilityRole="radiogroup" accessibilityLabel={label} style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{items.map(item=><Pressable key={item.value} accessibilityRole="radio" accessibilityState={{checked:value===item.value}} onPress={()=>onChange(item.value)} style={{paddingHorizontal:14,paddingVertical:12,minHeight:44,borderRadius:10,borderWidth:1,borderColor:value===item.value?colors.green:colors.border,backgroundColor:value===item.value?colors.mint:colors.surface}}><Text style={{fontSize:14,fontWeight:value===item.value?'700':'400',color:colors.ink}}>{item.label}</Text></Pressable>)}</View>;}
export function Field({label,value,onChange,multiline=false,secure=false,placeholder,keyboard='default'}:{label:string;value:string;onChange:(v:string)=>void;multiline?:boolean;secure?:boolean;placeholder?:string;keyboard?:'default'|'email-address'|'url'}){return <View style={{gap:8}}><Text style={[s.body,{fontWeight:'600'}]}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChange} multiline={multiline} secureTextEntry={secure} autoCapitalize={keyboard==='default'&&!secure?'sentences':'none'} autoCorrect={keyboard==='default'&&!secure} keyboardType={keyboard} placeholder={placeholder} placeholderTextColor={colors.muted} style={{borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,borderRadius:12,padding:14,minHeight:multiline?120:50,textAlignVertical:multiline?'top':'center',fontSize:16,color:colors.ink,lineHeight:24}}/></View>;}
export function Hint({children,tone='green'}:{children:ReactNode;tone?:'green'|'orange'}){return <View style={[s.note,{backgroundColor:tone==='orange'?colors.orangeLight:colors.mint}]}>{typeof children==='string'?<Text style={s.body}>{children}</Text>:children}</View>;}
export function Source({url}:{url:string}){return <Pressable accessibilityRole="link" onPress={()=>Linking.openURL(url).catch(()=>{})} style={{minHeight:44,justifyContent:'center'}}><Text style={[s.muted,{color:colors.green,textDecorationLine:'underline'}]}>Consultar la fuente ↗</Text></Pressable>;}
export function Action({title,subtitle,icon,onPress}:{title:string;subtitle:string;icon:IconName;onPress:()=>void}){return <Pressable accessibilityRole="button" onPress={onPress} style={({pressed})=>[s.panel,s.row,{opacity:pressed?.7:1,padding:17}]}><Icon name={icon} color={colors.green}/><View style={{flex:1,gap:4}}><Text style={[s.body,{fontWeight:'700'}]}>{title}</Text><Text style={s.muted}>{subtitle}</Text></View><Icon name="chevron-right" size={18}/></Pressable>;}
