import React from 'react';
import {Pressable,Text,View,StyleSheet,Modal} from 'react-native';
import Feather from '@expo/vector-icons/Feather';
import {colors,styles as s} from '../theme';
export type IconName=React.ComponentProps<typeof Feather>['name'];
export function Icon({name,size=23,color=colors.ink}:{name:IconName;size?:number;color?:string}){return <Feather name={name} size={size} color={color} accessible={false}/>;}
export function Button({label,onPress,secondary=false,disabled=false,icon}:{label:string;onPress:()=>void;secondary?:boolean;disabled?:boolean;icon?:IconName}){return <Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={({pressed})=>[u.button,{backgroundColor:secondary?colors.surface:colors.green,opacity:disabled?.4:pressed?.8:1}]}><Text style={[u.buttonText,{color:secondary?colors.ink:'#FFF'}]}>{label}</Text>{icon?<Icon name={icon} color={secondary?colors.ink:'#FFF'}/>:null}</Pressable>;}
export function Row({title,subtitle,icon,onPress,last=false}:{title:string;subtitle:string;icon:IconName;onPress:()=>void;last?:boolean}){return <Pressable accessibilityRole="button" onPress={onPress} style={({pressed})=>[u.listRow,{borderBottomWidth:last?0:1,backgroundColor:pressed?colors.mint:colors.surface}]}><Icon name={icon}/><View style={{flex:1,gap:3}}><Text style={[s.body,{fontWeight:'700'}]}>{title}</Text><Text style={s.muted}>{subtitle}</Text></View><Icon name="chevron-right" size={20}/></Pressable>;}
export function DemoNote(){return <Text style={[s.caption,{textAlign:'center'}]}>Preguntas de demostración · No es un examen oficial</Text>;}
export function Meter({value,label}:{value:number;label:string}){return <View accessibilityRole="progressbar" accessibilityLabel={label} accessibilityValue={{min:0,max:100,now:Math.round(value*100)}} style={u.track}><View style={[u.fill,{width:`${Math.max(0,Math.min(1,value))*100}%`}]}/></View>;}
export function ConfirmExit({visible,onStay,onExit}:{visible:boolean;onStay:()=>void;onExit:()=>void}){return <Modal visible={visible} transparent animationType="fade" onRequestClose={onStay}><View style={u.overlay}><View style={[s.panel,{width:'100%',maxWidth:390,padding:24,gap:18}]}><Text style={s.heading}>¿Dejar esta sesión?</Text><Text style={s.body}>Las respuestas corregidas se conservan. La sesión quedará sin completar.</Text><Button label="Seguir practicando" onPress={onStay}/><Button label="Salir de la sesión" secondary onPress={onExit}/></View></View></Modal>;}
const u=StyleSheet.create({button:{minHeight:54,paddingHorizontal:18,paddingVertical:14,borderRadius:10,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},buttonText:{fontSize:17,lineHeight:24,fontWeight:'700',flexShrink:1},listRow:{minHeight:90,padding:18,flexDirection:'row',alignItems:'center',gap:16,borderBottomColor:colors.border},track:{height:8,backgroundColor:'#E3E8EB',borderRadius:10,overflow:'hidden',flex:1},fill:{height:'100%',backgroundColor:colors.green,borderRadius:10},overlay:{flex:1,backgroundColor:'#172A3488',alignItems:'center',justifyContent:'center',padding:24}});
