import {useEffect,useState} from 'react';
import {Platform,Text,View} from 'react-native';
import {RecordingPresets,useAudioRecorder,useAudioRecorderState,requestRecordingPermissionsAsync,setAudioModeAsync} from 'expo-audio';
import {File} from 'expo-file-system';
import {Button} from './UI';
import {loadConnection,api} from '../services/api';
import {styles as s} from '../theme';
export function VoiceInput({onText}:{onText:(text:string)=>void}){const recorder=useAudioRecorder(RecordingPresets.HIGH_QUALITY);const state=useAudioRecorderState(recorder);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [available,setAvailable]=useState(false);const [uri,setUri]=useState<string|null>(null);useEffect(()=>{loadConnection().then(c=>{if(c)return api<{ai:boolean}>(c,'/api/health');return null;}).then(r=>setAvailable(!!r?.ai)).catch(()=>{});return()=>{if(recorder.isRecording)recorder.stop().catch(()=>{});};},[]);
 useEffect(()=>{if(state.isRecording&&state.durationMillis>=60000)stop();},[state.durationMillis]);
 async function start(){try{setError('');if(!(await requestRecordingPermissionsAsync()).granted)throw Error('Necesitas permitir el micrófono para dictar.');await setAudioModeAsync({allowsRecording:true,playsInSilentMode:true});await recorder.prepareToRecordAsync();recorder.record();setUri(null);}catch(e){setError((e as Error).message);}}
 async function stop(){try{await recorder.stop();setUri(recorder.uri);await setAudioModeAsync({allowsRecording:false});}catch(e){setError((e as Error).message);}}
 async function send(){if(!uri)return;setBusy(true);try{const c=await loadConnection();if(!c)throw Error('Conecta tu cuenta para transcribir.');let base64:string;if(Platform.OS==='web'){const blob=await (await fetch(uri)).blob();base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(blob);});}else base64=await new File(uri).base64();const r=await api<{text:string}>(c,'/api/transcribe',{audio:base64,mime:Platform.OS==='web'?'audio/webm':'audio/mp4'});onText(r.text);setUri(null);if(Platform.OS!=='web')try{new File(uri).delete();}catch{}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <View style={{gap:8}}><Button secondary label={state.isRecording?'Terminar grabación':available?'Dictar una nota':'Dictado: requiere tutor conectado'} disabled={!available||busy} icon="mic" onPress={state.isRecording?stop:start}/>{state.isRecording?<Text style={s.muted}>Grabando · {Math.floor(state.durationMillis/1000)} s · máximo 60 s</Text>:null}{uri?<><Text style={s.caption}>Al transcribir, este audio se enviará a tu servidor y a su proveedor de IA. Revisa el texto antes de guardarlo.</Text><Button label={busy?'Transcribiendo…':'Enviar audio para transcribir'} disabled={busy} onPress={send}/><Button secondary label="Descartar audio" onPress={()=>{if(Platform.OS!=='web')try{new File(uri).delete();}catch{}setUri(null);}}/></>:null}{error?<Text accessibilityRole="alert" style={s.muted}>{error}</Text>:null}</View>;
}
