import {createContext,useContext,useEffect,useRef,useState,type ReactNode} from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {initialPack} from '../data/catalog';
import {addAnswer,emptyProgress,mergeProgress,parseProgress,uid} from '../engine/progress';
import {validatePack} from '../engine/content';
import {examSelection,studySelection} from '../engine/learning';
import type {ActiveStudy,Answer,ContentPack,LessonNote,Progress,Question,SessionResult} from '../types';
export const PROGRESS_KEY='apunto.progress.v2';export const CONTENT_KEY='apunto.content.v2';
function useStore(){
 const [progress,setProgress]=useState<Progress>(emptyProgress);const [pack,setPack]=useState(initialPack);const [ready,setReady]=useState(false);const [error,setError]=useState<string|null>(null);const [notice,setNotice]=useState<string|null>(null);
 const ref=useRef(progress);const queue=useRef(Promise.resolve());const writable=useRef(false);
 useEffect(()=>{let alive=true;(async()=>{try{const values=await AsyncStorage.multiGet([PROGRESS_KEY,'apunto.progress.v1',CONTENT_KEY]);let content=initialPack;if(values[2][1]){try{content=validatePack(JSON.parse(values[2][1]));}catch{if(alive)setNotice('El paquete descargado no es válido. Se utiliza el contenido incluido en la app.');}}const data=parseProgress(values[0][1]??values[1][1],content);if(alive){ref.current=data;writable.current=true;setProgress(data);setPack(content);}}catch{if(alive)setError('No se pudo leer el progreso. Tus datos no se han sobrescrito. Puedes usar la app temporalmente sin guardar.');}finally{if(alive)setReady(true);}})();return()=>{alive=false;};},[]);
 const update=(fn:(p:Progress)=>Progress)=>{const next=fn(ref.current);ref.current=next;setProgress(next);if(writable.current){const snapshot=JSON.stringify(next);queue.current=queue.current.then(()=>AsyncStorage.setItem(PROGRESS_KEY,snapshot)).then(()=>setError(null)).catch(()=>setError('No se ha podido guardar el último cambio. Comprueba el espacio disponible.'));}};
 const beginStudy=(title:string,opts:{count?:number;conceptId?:string;review?:boolean;questions?:Question[]}={})=>{if(ref.current.activeStudy){setNotice('Tienes una sesión abierta. Puedes retomarla desde Hoy.');return false;}const bank=opts.questions??studySelection(pack,ref.current,opts);if(!bank.length){setNotice('No hay preguntas pendientes en este momento. Puedes practicar otro tema.');return false;}const now=new Date().toISOString();update(p=>({...p,activeStudy:{id:uid(),title,questions:bank,answers:[],index:0,selected:null,confidence:'unsure',helpUsed:false,checked:false,startedAt:now,questionStartedAt:now}}));return true;};
 const patchStudy=(patch:Partial<ActiveStudy>)=>update(p=>({...p,activeStudy:p.activeStudy?{...p.activeStudy,...patch}:null}));
 const checkStudy=()=>update(p=>{const a=p.activeStudy;if(!a||a.checked||a.selected===null)return p;const q=a.questions[a.index];const answer:Answer={id:`${a.id}-${a.index}`,questionId:q.id,questionVersion:q.version,concepts:q.concepts,family:q.family,choice:a.selected,correct:a.selected===q.correct,at:new Date().toISOString(),elapsedMs:Math.max(0,Date.now()-Date.parse(a.questionStartedAt)),confidence:a.confidence,helpUsed:a.helpUsed,mode:q.sceneId?'scene':'study',sessionId:a.id};const next=addAnswer(p,answer);return {...next,activeStudy:{...a,checked:true,answers:[...a.answers,answer]}};});
 const completeStudy=():SessionResult|null=>{const a=ref.current.activeStudy;if(!a||!a.checked||a.index!==a.questions.length-1)return null;const session:SessionResult={id:a.id,title:a.title,at:new Date().toISOString(),total:a.questions.length,correct:a.answers.filter(x=>x.correct).length,mode:'study',unseen:0,elapsedMs:Math.max(0,Date.now()-Date.parse(a.startedAt))};update(p=>({...p,sessions:p.sessions.some(s=>s.id===session.id)?p.sessions:[session,...p.sessions],activeStudy:null}));return session;};
 const nextStudy=()=>{const a=ref.current.activeStudy;if(!a?.checked)return;patchStudy({index:a.index+1,selected:null,checked:false,confidence:'unsure',helpUsed:false,questionStartedAt:new Date().toISOString()});};
 const beginExam=()=>{const bank=examSelection(pack,ref.current);if(bank.length<30){setNotice('Se necesitan al menos 30 preguntas de evaluación activas. Actualiza el contenido.');return false;}const seen=new Set(ref.current.answers.map(a=>a.questionId));update(p=>({...p,activeExam:{id:uid(),questions:bank,choices:{},flags:[],index:0,startedAt:new Date().toISOString(),deadline:new Date(Date.now()+30*60000).toISOString(),unseen:bank.filter(q=>!seen.has(q.id)).length}}));return true;};
 const finishExam=():SessionResult|null=>{const e=ref.current.activeExam;if(!e)return null;const at=new Date().toISOString();const items=e.questions.map(q=>({questionId:q.id,choice:e.choices[q.id]??null,correct:e.choices[q.id]===q.correct}));const session:SessionResult={id:e.id,title:'Simulacro de práctica',at,total:e.questions.length,correct:items.filter(a=>a.correct).length,mode:'exam',unseen:e.unseen,elapsedMs:Math.min(30*60000,Math.max(0,Date.now()-Date.parse(e.startedAt))),answers:items};update(p=>{let next=p;for(const q of e.questions){const choice=e.choices[q.id];if(choice!==undefined)next=addAnswer(next,{id:`${e.id}-${q.id}`,questionId:q.id,questionVersion:q.version,concepts:q.concepts,family:q.family,choice,correct:choice===q.correct,at,elapsedMs:0,confidence:e.flags.includes(q.id)?'unsure':'sure',helpUsed:false,mode:'exam',sessionId:e.id});}return {...next,activeExam:null,sessions:next.sessions.some(s=>s.id===session.id)?next.sessions:[session,...next.sessions]};});return session;};
 const bookmark=(q:Question)=>update(p=>{const old=p.bookmarks.find(b=>b.questionId===q.id);return {...p,bookmarks:[...p.bookmarks.filter(b=>b.questionId!==q.id),{questionId:q.id,active:!old?.active,updatedAt:new Date().toISOString()}]};});
 const saveNote=(note:LessonNote)=>update(p=>({...p,notes:[note,...p.notes.filter(n=>n.id!==note.id)]}));
 const updatePack=async(next:ContentPack)=>{validatePack(next);if(next.version<=pack.version)return false;await AsyncStorage.setItem(CONTENT_KEY,JSON.stringify(next));setPack(next);update(p=>({...p,activeStudy:null,activeExam:null}));setNotice('Contenido actualizado. Se han cerrado las sesiones abiertas para evitar preguntas de versiones anteriores.');return true;};
 return {progress,pack,ready,error,notice,setNotice,update,beginStudy,patchStudy,checkStudy,nextStudy,completeStudy,beginExam,finishExam,bookmark,saveNote,updatePack,merge:(remote:Progress)=>update(p=>mergeProgress(p,remote)),flush:()=>queue.current};
}
type Store=ReturnType<typeof useStore>;const Context=createContext<Store|null>(null);
export function StoreProvider({children}:{children:ReactNode}){return <Context.Provider value={useStore()}>{children}</Context.Provider>;}
export function useApp(){const s=useContext(Context);if(!s)throw new Error('Missing StoreProvider');return s;}
